#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

# shellcheck disable=SC2086
exec s6-setuidgid hotio python3 "${APP_DIR}/qbit_manage.py" --config-file "${CONFIG_DIR}/config.yml" --log-file "${CONFIG_DIR}/qbitmanage.log" ${ARGS}
