#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ -z "${QBT_CONFIG}" ]] && [[ -z "${QBT_CONFIG_DIR}" ]]; then
    export QBT_CONFIG_DIR="${CONFIG_DIR}"
fi

# shellcheck disable=SC2086
exec s6-setuidgid hotio python3 "${APP_DIR}/qbit_manage.py" ${ARGS}
