#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
ARGS=${ARGS}
----------------------------------------------------------------------
"

if [[ ! -f "${CONFIG_DIR}/config.yml" ]] && [[ -z "${QBT_CONFIG}" ]]; then
    echo "Installing default \"config.yml\", modify this file or set \"QBT_CONFIG\" env variable..."
    cp "${APP_DIR}/config/config.yml.sample" "${CONFIG_DIR}/config.yml"
    find "${CONFIG_DIR}/config.yml" \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi
