#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
ARGS=${ARGS}
----------------------------------------------------------------------
"

##################################################
# Should be removed once new version is released #
if [[ ! -f "${CONFIG_DIR}/config.yml" ]] && [[ -z "${QBT_CONFIG}" ]] && [[ -z "${QBT_CONFIG_DIR}" ]]; then
    echo "Installing default \"config.yml\"..."
    cp "${APP_DIR}/config/config.yml.sample" "${CONFIG_DIR}/config.yml"
    find "${CONFIG_DIR}/config.yml" \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi
##################################################
