#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
ARGS=${ARGS}
----------------------------------------------------------------------
"

if [[ ! -f "${CONFIG_DIR}/config.yml" ]]; then
    echo "Installing default \"config.yml\"..."
    cp "${APP_DIR}/config/config.yml.sample" "${CONFIG_DIR}/config.yml"
    chown hotio:hotio -R "${CONFIG_DIR}/config.yml"
fi
