#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=${PUID}
PGID=${PGID}
UMASK=${UMASK}
TZ=${TZ}
ARGS=${ARGS}
----------------------------------------------------------------------
"

if [[ ! "${PUID}" -eq 0 ]] && [[ ! "${PGID}" -eq 0 ]]; then
    echo "Executing usermod..."
    mkdir "/tmp/temphome"
    usermod -d "/tmp/temphome" hotio
    usermod -o -u "${PUID}" hotio
    usermod -d "${CONFIG_DIR}" hotio
    rm -rf "/tmp/temphome"
    groupmod -o -g "${PGID}" hotio
else
    echo "Running as root is not supported, please fix your PUID and PGID!"
    exit 1
fi

echo "Applying permissions to ${CONFIG_DIR}"
chmod "=rwx" "${CONFIG_DIR}"
chown hotio:hotio "${CONFIG_DIR}"

if [[ ! -f "${CONFIG_DIR}/config.yml" ]]; then
    echo "Installing default \"config.yml\"..."
    cp "${APP_DIR}/config/config.yml.sample" "${CONFIG_DIR}/config.yml"
    chown hotio:hotio -R "${CONFIG_DIR}/config.yml"
fi
